---
abstract: 'Parses an X.509 certificate revocation list'
author:
  - 'Duncan Segrest'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.46, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Crypt-X509-CRL
no_index:
  directory:
    - t
    - inc
requires:
  Convert::ASN1: '0.19'
  perl: '5.006'
version: '0.4'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
